// <auto-generated />
using System;
using CarQuery__Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarQuery__Test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240530002025_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarQuery__Test.Domain.Models.Car", b =>
                {
                    b.Property<int>("idCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCar"));

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("color")
                        .HasColumnType("tinyint");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("idCar");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarQuery__Test.Domain.Models.Reseller", b =>
                {
                    b.Property<int>("idReseller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReseller"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("classification")
                        .HasColumnType("tinyint");

                    b.Property<string>("nameReseller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idReseller");

                    b.ToTable("Resellers");
                });

            modelBuilder.Entity("CarQuery__Test.Domain.Models.Sale", b =>
                {
                    b.Property<int>("idSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSale"));

                    b.Property<DateTime>("DthRegister")
                        .HasColumnType("datetime2");

                    b.Property<int?>("caridCar")
                        .HasColumnType("int");

                    b.Property<int?>("clientidUser")
                        .HasColumnType("int");

                    b.Property<int>("fk_idCar")
                        .HasColumnType("int");

                    b.Property<int>("fk_idClient")
                        .HasColumnType("int");

                    b.Property<int>("fk_idReseller")
                        .HasColumnType("int");

                    b.Property<int>("fk_idSeller")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("reselleridReseller")
                        .HasColumnType("int");

                    b.Property<int?>("selleridUser")
                        .HasColumnType("int");

                    b.HasKey("idSale");

                    b.HasIndex("caridCar");

                    b.HasIndex("clientidUser");

                    b.HasIndex("reselleridReseller");

                    b.HasIndex("selleridUser");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("CarQuery__Test.Domain.Models.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUser"));

                    b.Property<DateOnly>("birth")
                        .HasColumnType("date");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("sex")
                        .HasColumnType("tinyint");

                    b.Property<byte>("userType")
                        .HasColumnType("tinyint");

                    b.HasKey("idUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarQuery__Test.Domain.Models.Sale", b =>
                {
                    b.HasOne("CarQuery__Test.Domain.Models.Car", "car")
                        .WithMany()
                        .HasForeignKey("caridCar");

                    b.HasOne("CarQuery__Test.Domain.Models.User", "client")
                        .WithMany()
                        .HasForeignKey("clientidUser");

                    b.HasOne("CarQuery__Test.Domain.Models.Reseller", "reseller")
                        .WithMany()
                        .HasForeignKey("reselleridReseller");

                    b.HasOne("CarQuery__Test.Domain.Models.User", "seller")
                        .WithMany()
                        .HasForeignKey("selleridUser");

                    b.Navigation("car");

                    b.Navigation("client");

                    b.Navigation("reseller");

                    b.Navigation("seller");
                });
#pragma warning restore 612, 618
        }
    }
}
